services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: linnarope
      POSTGRES_PASSWORD: linnarope
      POSTGRES_DB: linnarope
      POSTGRES_INITDB_ARGS: '--locale en_US.UTF-8'
    volumes:
      - ./psql-setup:/docker-entrypoint-initdb.d
    networks:
      - stupid_gha_network
      
networks:
  stupid_gha_network:
    driver: bridge
